### ISSUE TITLE
Should the SDK make `custom_fields` more usable?

### ISSUE THREAD

**Issue by ADSKLowenthal** [uservoice/uservoice-nodejs#1]
https://github.com/uservoice/uservoice-nodejs/blob/master/src/v1/api/models/ticket.ts#L51

The v1 API returns `custom_fields` as an array of objects, with key and value:

``` js
[
  {key: 'key1', value: 'value1'},
  {key: 'key2', value: 'value2'},
  {key: 'key3', value: 'value3'}
]
```

This requires additional work outside of the SDK to get to the values.
For example (with lodash):
`ticket.custom_field['Custom Field']` vs. `_.find(ticket.custom_fields, ['key', 'Custom Field']).value`

Would it be better to have the SDK collapse these into a standard JSON object, with the keys as indexes?  
Offhand I can't think of anything that would be lost. They would still be easily iterable with native JS code, but then also easily accessible by specific keys.

**Comment by lukeautry** [comment]
Agreed, let me know what you think: https://github.com/uservoice/uservoice-nodejs/pull/2

**Comment by ADSKLowenthal** [comment]
#2 looks good to solve this.
