### ISSUE TITLE
How to handle versioning?

### ISSUE THREAD

**Issue by ADSKLowenthal** [uservoice/uservoice-nodejs#3]
Referencing #1, and #2 as its solution. We end up in a position where 1.0.x and 1.0.x+1 brings a breaking change.

Issues like this are more foundational to how we'd like the SDK to work, versus features and fixes.

We should have a versioning plan to make it possible to understand compatibility between changes. I typically like using SemVer http://semver.org/ but just suggesting there should be something codified.

With SemVer reverting to 0.x.y would allow us to kick the tires and make updates like this. Alternatively, without reverting, we could modify it to allow for breaking changes at minor (major.minor.build) version increments. Or possibly treat 1.x similar to 0.x and look towards 2.x to be a more stable versioned release.

Should also consider the impact of a production release of api v2 in the future.

**Comment by attack7** [comment]
I'd certainly be in favor of semver as well.

**Comment by lukeautry** [comment]
I think semver is a good choice.

Given the fact that this code hasn't seen much action in the wild (outside of our own testing), I would say setting the version to something like 0.0.12 would be reasonable, with the expectation that we may  find substantial problems that require breaking changes.

**Comment by ADSKLowenthal** [comment]
Will we have any issues around NPM if we revert to a previous version?

**Comment by lukeautry** [comment]
It should just work afaik if we change it in the package.json.

**Comment by lukeautry** [comment]
Merged the changes with v. 0.0.11 - seems like the version on uservoice-nodejs updated as expected: https://www.npmjs.com/package/uservoice-nodejs

Everything look good here?

**Comment by lukeautry** [comment]
Also, added some stuff to the readme about this subject: https://github.com/uservoice/uservoice-nodejs#versioning
