### ISSUE TITLE
Receiving `indexOf` error when searching for tickets

### ISSUE THREAD

**Issue by ADSKLowenthal** [uservoice/uservoice-nodejs#4]
We're getting intermittent errors (log below) from the SDK. Tracking it down it looks like an issue with Search. Here's the code that spawns the issue:

``` js
return uservoice.ticketService.search(query)
            .then(function(response) {
              res.status(200).json(
                {
                  tickets: response.tickets,
                  projects: projectsById,
                  projectsByGameware: projectsByGameware
                });
            })
            .catch(function(err) {
              console.error(err);
              next(err);
            });
```

My assumption right now is that the search is coming up empty, and `processTicketListResponseCustomFields` isn't handling that correctly.

ticketService.ts:60

``` js
private processTicketListResponseCustomFields(ticketListResponse: ITicketListResponse) {
    ticketListResponse.tickets.forEach(t => this.convertCustomFieldsToObject(t));
    return ticketListResponse;
  }
```

I'm going to try a check for `ticketListResponse.tickets.length` and skip the forEach call if it's 0.

> TypeError: Cannot read property 'indexOf' of undefined at NotFoundHandler (/usr/src/app/node_modules/meanio/lib/core_modules/server/ExpressEngine.js:152:19) at Layer.handle_error (/usr/src/app/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/layer.js:71:5) at trim_prefix (/usr/src/app/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:310:13) at /usr/src/app/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:280:7 at Function.process_params (/usr/src/app/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:330:12) at next (/usr/src/app/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/index.js:271:10) at next (/usr/src/app/node_modules/meanio/lib/core_modules/server/node_modules/express/lib/router/route.js:121:14) at /usr/src/app/packages/custom/gdTickets/server/controllers/tickets.js:210:15 at tryCatcher (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/promise.js:504:31) at Promise._settlePromise (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/promise.js:561:18) at Promise._settlePromise0 (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/promise.js:606:10) at Promise._settlePromises (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/promise.js:681:18) at Async._drainQueue (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/async.js:138:16) at Async._drainQueues (/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/async.js:148:10) at Immediate.Async.drainQueues [as _onImmediate](/usr/src/app/packages/custom/gdTickets/node_modules/uservoice-nodejs/node_modules/bluebird/js/release/async.js:17:14) at tryOnImmediate (timers.js:534:15) at processImmediate [as _immediateCallback](timers.js:514:5)

**Comment by lukeautry** [comment]
Hmm, this is pretty odd. Even if there are no search results, the API should return an empty array, e.g.

`
{ response_data:
   { query: 'test123',
     page: 1,
     per_page: 500,
     total_records: 0,
     filter: 'all',
     sort: 'newest' },
  tickets: [] }
`

Checking for tickets.length shouldn't make any difference here if it were an empty array - forEach just wouldn't do anything. tickets itself must be undefined. We can check to make sure tickets is defined, but even if it isn't, we've just moved the error up from processTicketListResponseCustomFields to your success handler code.

Is there any way you can debug this and see exactly what the return data is?

**Comment by ADSKLowenthal** [comment]
Yep, I'm looking through it now.

**Comment by ADSKLowenthal** [comment]
Yea, this one is on us. We're building a query for search by joining an array of terms. However, that array is empty in some cases, so the search ends up being something like `"Project Id":,` which the API does not like.
