### ISSUE TITLE
V2 Client loginAsOwner failed

### ISSUE THREAD

**Issue by bigfoam** [uservoice/uservoice-nodejs#5]
I tried v2Client.loginAsOwner with a valid apiSecret but got the errors below in the browser console:

`XMLHttpRequest cannot load https://sitebuilder.uservoice.com/api/v2/oauth/token. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://instantpage.dev-godaddy.com:8443' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.`

Also, I'm not quite sure how to set `subdomain` for my application due to lack of description on this parameter. Hope anyone can give me some hint on this.

**Comment by jcamenisch** [comment]
@bigfoam, unfortunately, this library does not support use of the API from the browser. The main problem is that your API secret has to be kept secret, so allowing browsers to download it is not an option.

If a server-side node application is what you're working toward, try this in that environment.

In the example you provided, your subdomain would be "sitebuilder." I hope that helps.
