### ISSUE TITLE
oauth as a private repo

### ISSUE THREAD

**Issue by bigfoam** [uservoice/uservoice-nodejs#6]
I noticed that node-oauth is still using a PR version. Would you please merge it to the master since already had +1? Our server somehow treat it as a private repo and caused a lot of trouble.

Thanks,
Max

**Comment by adskjohn** [comment]
Same issue here.  We can no longer npm install uservoice-nodejs because of the dependency on a private or deleted repository of lukeautry/node-oauth.  Either the repository needs to come back or the package.json needs to be updated 

@lukeautry Tagging you since it was one of your repos

**Comment by lukeautry** [comment]
@bigfoam @adskjohn Sorry about that - we're using the main repo now. I've updated the dependency in version 0.0.12.

Let me know if you're still having trouble after the update.
